dist: trusty

language: php

cache:
    apt: true

addons:
    apt:
        packages:
            - libxml2-utils

before_install:
    - export XMLLINT_INDENT="	"

script:
    # Make sure all packages used are valid.
    - composer install
    # Validate the composer.json file.
    - composer validate --strict
    # Validate the xml files.
    # @link http://xmlsoft.org/xmllint.html
    - xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd ./WP-QA-Basic/ruleset.xml
    - xmllint --noout --schema ./vendor/squizlabs/php_codesniffer/phpcs.xsd ./WP-QA-Strict/ruleset.xml
    # Check the code-style consistency of the xml files.
    - diff -B ./WP-QA-Basic/ruleset.xml <(xmllint --format "./WP-QA-Basic/ruleset.xml")
    - diff -B ./WP-QA-Strict/ruleset.xml <(xmllint --format "./WP-QA-Strict/ruleset.xml")
    # Check the code-style of the PHP code.
    - vendor/bin/phpcs
